Profiles:
  OrdererGenesis:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V1_3: true
    Orderer:
      OrdererType: etcdraft
      Addresses:
      - orderer0.orderer:7050
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Kafka:
        Brokers: []
      EtcdRaft:
        Consenters:
        - Host: orderer0.orderer
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/orderer/orderers/orderer0.orderer/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/orderer/orderers/orderer0.orderer/tls/server.crt
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
          Type: ImplicitMeta
          Rule: ANY Writers
      Organizations:
      - Name: Orderer
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/orderer/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
          Writers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
          Admins:
            Type: Signature
            Rule: OR('OrdererMSP.admin')
        AnchorPeers: []
      Capabilities:
        V1_1: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Org1
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
            Writers:
              Type: Signature
              Rule: OR('Org1MSP.admin', 'Org1MSP.client')
            Admins:
              Type: Signature
              Rule: OR('Org1MSP.admin')
          AnchorPeers:
          - Host: peer0.org1
            Port: 7051
        - Name: Org2
          ID: Org2MSP
          MSPDir: crypto-config/peerOrganizations/org2/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')
            Writers:
              Type: Signature
              Rule: OR('Org2MSP.admin', 'Org2MSP.client')
            Admins:
              Type: Signature
              Rule: OR('Org2MSP.admin')
          AnchorPeers:
          - Host: peer0.org2
            Port: 7051
  OrgsChannel:
    Consortium: SampleConsortium
    Application:
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
      Organizations:
      - Name: Org1
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
          Writers:
            Type: Signature
            Rule: OR('Org1MSP.admin', 'Org1MSP.client')
          Admins:
            Type: Signature
            Rule: OR('Org1MSP.admin')
        AnchorPeers:
        - Host: peer0.org1
          Port: 7051
      - Name: Org2
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')
          Writers:
            Type: Signature
            Rule: OR('Org2MSP.admin', 'Org2MSP.client')
          Admins:
            Type: Signature
            Rule: OR('Org2MSP.admin')
        AnchorPeers:
        - Host: peer0.org2
          Port: 7051
      Capabilities:
        V1_3: true
        V1_2: false
        V1_1: false
